#!/bin/bash

while getopts ":g:r:" arg;
do
	usr=$OPTARG
	case $arg in
		g)
			
			usermod -a -G grantSSHGroup $usr
			;;
		r)
			gpasswd -d $usr grantSSHGroup
			usermod -a -G denySSHGroup $usr
			;;
		esac
done
